name: django-mini-app
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: make run-django
    networks:
      backend_bridge:
        ipv4_address: 100.102.88.101
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  backend_bridge:
    external: true
