FROM python:3.12

ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y netcat-openbsd net-tools && \
    pip install -U pip

WORKDIR /app
COPY ./requirements-dev.txt /app/requirements-dev.txt

RUN pip install -r requirements-dev.txt
