# Generated by Django 5.0.6 on 2024-06-28 06:09

import django.db.models.deletion
from django.db import migrations, models

import app.core.common.db_date


class Migration(migrations.Migration):
    """Миграция для создания моделей Account и Slot."""

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0006_remove_customer_has_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tg_id", models.BigIntegerField(help_text="Telegram ID")),
                ("first_name", models.CharField(help_text="First name", max_length=255)),
                ("last_name", models.CharField(help_text="Last name", max_length=255, null=True)),
                ("username", models.CharField(help_text="Username", max_length=255, null=True)),
                ("init_data", models.CharField(help_text="Init data", max_length=4096)),
                ("proxy_url", models.CharField(help_text="Proxy URL", max_length=2048, null=True)),
                ("is_playing", models.BooleanField(default=False, help_text="Is account playing")),
                ("auth_token", models.CharField(help_text="Auth token", max_length=2048, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"
                    ),
                ),
            ],
            options={
                "unique_together": {("tg_id", "customer", "game")},
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "expired_at",
                    models.DateTimeField(
                        db_index=True, default=app.core.common.db_date.utc_now_plus_month, help_text="Slot expired at"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account", null=True, on_delete=django.db.models.deletion.RESTRICT, to="games.account"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"
                    ),
                ),
            ],
        ),
    ]
