# Generated by Django 5.0.6 on 2024-06-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для создания моделей игр."""

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0003_alter_customer_last_name_alter_customer_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                ("id", models.BigIntegerField(help_text="Telegram ID", primary_key=True, serialize=False)),
                ("first_name", models.CharField(help_text="Telegram first name", max_length=255)),
                ("last_name", models.CharField(help_text="Telegram last name", max_length=255, null=True)),
                ("username", models.CharField(help_text="Telegram username", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("init_data", models.CharField(help_text="Account init data", max_length=4096)),
                ("proxy_url", models.CharField(help_text="Account proxy URL", max_length=2048)),
                ("is_playing", models.BooleanField(default=False, help_text="Is account playing")),
                (
                    "info",
                    models.ForeignKey(
                        help_text="Account info", on_delete=django.db.models.deletion.RESTRICT, to="games.info"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expire_time", models.DateTimeField(help_text="Slot expire time")),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account", null=True, on_delete=django.db.models.deletion.RESTRICT, to="games.account"
                    ),
                ),
                (
                    "hash_name",
                    models.ForeignKey(
                        help_text="Game hash name", on_delete=django.db.models.deletion.RESTRICT, to="core.game"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="User ID", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
                    ),
                ),
            ],
        ),
    ]
