# Generated by Django 5.0.6 on 2024-06-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для удаления полей hash_name и user_id из модели Slot и добавления полей game и user."""

    dependencies = [
        ("core", "0001_initial"),
        ("games", "0001_initial"),
        ("users", "0003_alter_customer_last_name_alter_customer_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="hash_name",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="user_id",
        ),
        migrations.AddField(
            model_name="slot",
            name="game",
            field=models.ForeignKey(help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slot",
            name="user",
            field=models.ForeignKey(
                help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="info",
            field=models.ForeignKey(help_text="Info", on_delete=django.db.models.deletion.RESTRICT, to="games.info"),
        ),
        migrations.AlterField(
            model_name="account",
            name="init_data",
            field=models.CharField(help_text="Init data", max_length=4096),
        ),
        migrations.AlterField(
            model_name="account",
            name="proxy_url",
            field=models.CharField(help_text="Proxy URL", max_length=2048),
        ),
        migrations.AlterField(
            model_name="info",
            name="first_name",
            field=models.CharField(help_text="First name", max_length=255),
        ),
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.BigIntegerField(help_text="User ID", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="info",
            name="last_name",
            field=models.CharField(help_text="Last name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="username",
            field=models.CharField(help_text="Username", max_length=255, null=True),
        ),
    ]
