# Generated by Django 5.0.6 on 2024-06-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения полей модели Account и Slot."""

    dependencies = [
        ("core", "0002_payment_created_at_alter_customer_first_name_and_more"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="auth_token",
            field=models.CharField(help_text="Auth token", null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(help_text="First name"),
        ),
        migrations.AlterField(
            model_name="account",
            name="init_data",
            field=models.TextField(help_text="Init data"),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(help_text="Last name", null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="proxy_url",
            field=models.CharField(help_text="Proxy URL", null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(help_text="Username", null=True),
        ),
        migrations.AlterField(
            model_name="slot",
            name="payment",
            field=models.ForeignKey(
                help_text="Payment",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="slot",
                to="core.payment",
            ),
        ),
    ]
