# Generated by Django 5.0.6 on 2024-06-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения поля slot.account."""

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="account",
            field=models.OneToOneField(
                help_text="Account",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="slot",
                to="games.account",
            ),
        ),
    ]
