# Generated by Django 5.0.6 on 2024-06-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения полей модели Slot."""

    dependencies = [
        ("core", "0001_initial"),
        ("games", "0002_alter_slot_account"),
        ("users", "0006_remove_customer_has_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="account",
            field=models.OneToOneField(
                help_text="Account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot",
                to="games.account",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="customer",
            field=models.ForeignKey(
                help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="game",
            field=models.ForeignKey(help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"),
        ),
    ]
