# Generated by Django 5.0.6 on 2024-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля user_agent и изменения поля auth_token в модели Account."""

    dependencies = [
        ("games", "0002_alter_account_auth_token_alter_account_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user_agent",
            field=models.CharField(help_text="User agent"),
        ),
        migrations.AlterField(
            model_name="account",
            name="auth_token",
            field=models.CharField(help_text="Auth token"),
        ),
    ]
