# Generated by Django 5.0.6 on 2024-06-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Мигоация для изменения полей модели Account и Slot."""

    dependencies = [
        ("core", "0001_initial"),
        ("games", "0002_remove_slot_hash_name_remove_slot_user_id_slot_game_and_more"),
        ("users", "0003_alter_customer_last_name_alter_customer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="info",
            field=models.OneToOneField(help_text="Info", on_delete=django.db.models.deletion.RESTRICT, to="games.info"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="account",
            field=models.OneToOneField(
                help_text="Account", on_delete=django.db.models.deletion.RESTRICT, to="games.account"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slot",
            name="game",
            field=models.OneToOneField(help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="user",
            field=models.OneToOneField(
                help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
            ),
        ),
    ]
