# Generated by Django 5.0.6 on 2024-06-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения полей модели Account."""

    dependencies = [
        ("core", "0001_initial"),
        ("games", "0003_alter_slot_account_alter_slot_customer_and_more"),
        ("users", "0006_remove_customer_has_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                help_text="User", on_delete=django.db.models.deletion.RESTRICT, to="users.customer"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="game",
            field=models.ForeignKey(help_text="Game", on_delete=django.db.models.deletion.RESTRICT, to="core.game"),
        ),
    ]
