# Generated by Django 5.0.6 on 2024-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для удаления поля expire_time и добавления поля expired_at в модель Slot."""

    dependencies = [
        ("games", "0003_alter_account_info_alter_slot_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="expire_time",
        ),
        migrations.AddField(
            model_name="slot",
            name="expired_at",
            field=models.DateTimeField(help_text="Slot expired at"),
            preserve_default=False,
        ),
    ]
