# Generated by Django 5.0.6 on 2024-07-04 19:04

import django.db.models.deletion
from django.db import migrations, models

import app.core.common.db_date


class Migration(migrations.Migration):
    """Миграция для создания модели сессии."""

    dependencies = [
        ("games", "0003_account_user_agent_alter_account_auth_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("errors", models.IntegerField(default=0, help_text="Errors Streak Counter")),
                ("next_at", models.DateTimeField(default=app.core.common.db_date.utc_now, help_text="Next at")),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="games.account",
                    ),
                ),
            ],
        ),
    ]
