# Generated by Django 5.0.6 on 2024-06-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения поля account модели Slot."""

    dependencies = [
        ("games", "0004_remove_slot_expire_time_slot_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="account",
            field=models.OneToOneField(
                help_text="Account", null=True, on_delete=django.db.models.deletion.RESTRICT, to="games.account"
            ),
        ),
    ]
