# Generated by Django 5.0.6 on 2024-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля is_payed в модель Slot."""

    dependencies = [
        ("games", "0004_alter_account_customer_alter_account_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="is_payed",
            field=models.BooleanField(default=False, help_text="Is slot payed"),
        ),
    ]
