# Generated by Django 5.0.6 on 2024-06-27 22:51

from django.db import migrations, models

import app.core.common.db_date


class Migration(migrations.Migration):
    """Миграция для изменения поля expired_at модели Slot."""

    dependencies = [
        ("games", "0005_alter_slot_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="expired_at",
            field=models.DateTimeField(
                db_index=True, default=app.core.common.db_date.utc_now_plus_month, help_text="Slot expired at"
            ),
        ),
    ]
