# Generated by Django 5.0.6 on 2024-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля auth_token в модель Account."""

    dependencies = [
        ("games", "0006_alter_slot_expired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="auth_token",
            field=models.CharField(help_text="Auth token", max_length=2048, null=True),
        ),
    ]
