# Generated by Django 5.0.6 on 2024-06-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для создания моделей Network и Play."""

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "success_percent",
                    models.DecimalField(decimal_places=2, default=0, help_text="Stat Success Percent", max_digits=5),
                ),
                ("success", models.BigIntegerField(default=0, help_text="Stat Success")),
                ("errors", models.BigIntegerField(default=0, help_text="Stat Errors")),
                ("errors_codes", models.JSONField(default=dict, help_text="Stat Error Codes")),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network",
                        to="games.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.BigIntegerField(default=0, help_text="Balance")),
                ("pph", models.BigIntegerField(default=0, help_text="PPH")),
                ("pphd", models.BigIntegerField(default=0, help_text="Stat PPHD")),
                ("taps", models.BigIntegerField(default=0, help_text="Stat Taps")),
                ("cards", models.BigIntegerField(default=0, help_text="Stat Bought Cards")),
                ("tasks", models.BigIntegerField(default=0, help_text="Stat Tasks")),
                ("combos", models.BigIntegerField(default=0, help_text="Stat Combos")),
                ("ciphers", models.BigIntegerField(default=0, help_text="Stat Ciphers")),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play",
                        to="games.account",
                    ),
                ),
            ],
        ),
    ]
