# Generated by Django 5.0.6 on 2024-07-05 14:00

from typing import TYPE_CHECKING, cast

from django.db import migrations, models

from app.core.apps.core.models import Game
from app.core.apps.stats.dicts.hamster import HamsterStatsSchema
from app.core.apps.stats.models import Play

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_stats_dict(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    """Замена данных в статистике на новые."""
    model_play = cast(Play, apps.get_model("stats", "Play"))
    model_play.objects.filter(account__game_id=Game.LITERAL_HAMSTER_KOMBAT).update(
        stats_dict=HamsterStatsSchema.get_hamster_dict()
    )


class Migration(migrations.Migration):
    """Миграция для удаления полей и добавления поля stats_dict."""

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="play",
            name="cards",
        ),
        migrations.RemoveField(
            model_name="play",
            name="ciphers",
        ),
        migrations.RemoveField(
            model_name="play",
            name="combos",
        ),
        migrations.RemoveField(
            model_name="play",
            name="pph",
        ),
        migrations.RemoveField(
            model_name="play",
            name="pphd",
        ),
        migrations.RemoveField(
            model_name="play",
            name="taps",
        ),
        migrations.RemoveField(
            model_name="play",
            name="tasks",
        ),
        migrations.AddField(
            model_name="play",
            name="stats_dict",
            field=models.JSONField(default=dict, help_text="Stats Dict"),
        ),
        migrations.RunPython(
            code=update_stats_dict,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
