# Generated by Django 5.0.6 on 2024-06-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения полей модели Network и Play."""

    dependencies = [
        ("games", "0004_alter_account_customer_alter_account_game"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="account",
            field=models.OneToOneField(
                help_text="Account", on_delete=django.db.models.deletion.CASCADE, to="games.account"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="account",
            field=models.OneToOneField(
                help_text="Account", on_delete=django.db.models.deletion.CASCADE, to="games.account"
            ),
        ),
    ]
