# Generated by Django 5.0.6 on 2024-06-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для создания модели Network."""

    dependencies = [
        ("games", "0003_alter_account_info_alter_slot_account_and_more"),
        ("stats", "0002_alter_play_unique_together_play_balance_play_cards_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "success_percent",
                    models.DecimalField(decimal_places=2, default=100, help_text="Stat Success Percent", max_digits=5),
                ),
                ("success", models.BigIntegerField(default=0, help_text="Stat Success")),
                ("errors", models.BigIntegerField(default=0, help_text="Stat Errors")),
                ("errors_codes", models.JSONField(default=dict, help_text="Stat Error Codes")),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account", on_delete=django.db.models.deletion.RESTRICT, to="games.account"
                    ),
                ),
            ],
        ),
    ]
