# Generated by Django 5.0.6 on 2024-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения поля success_percent модели Network."""

    dependencies = [
        ("stats", "0003_play_pphd_alter_network_account_alter_play_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="success_percent",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Stat Success Percent", max_digits=5),
        ),
    ]
