# Generated by Django 5.0.6 on 2024-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для создания модели Customer."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("refresh_token", models.CharField(db_index=True, max_length=256)),
            ],
        ),
    ]
