# Generated by Django 5.0.6 on 2024-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения полей модели Customer."""

    dependencies = [
        ("users", "0002_alter_customer_first_name_alter_customer_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(help_text="Last name", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(help_text="Username", max_length=150, null=True),
        ),
    ]
