# Generated by Django 5.0.6 on 2024-06-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля has_trial в модель Customer."""

    dependencies = [
        ("users", "0003_alter_customer_last_name_alter_customer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="has_trial",
            field=models.BooleanField(default=True, help_text="Has trial"),
        ),
    ]
