# Generated by Django 5.0.6 on 2024-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для удаления поля is_active и добавления поля has_banned в модель Customer."""

    dependencies = [
        ("users", "0004_customer_has_trial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.AddField(
            model_name="customer",
            name="has_banned",
            field=models.BooleanField(db_index=True, default=False, help_text="Is banned"),
        ),
    ]
