# Generated by Django 5.0.6 on 2024-06-27 19:53

from django.db import migrations


class Migration(migrations.Migration):
    """Миграция для удаления поля has_banned из модели Customer."""

    dependencies = [
        ("users", "0005_remove_customer_is_active_customer_has_banned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="has_banned",
        ),
    ]
