# Generated by Django 5.0.6 on 2024-06-27 16:27
from typing import TYPE_CHECKING, cast

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

    from app.core.apps.core.models import Game  # noqa: F401


def add_initial_game(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    """Добавление начальной игры."""
    hash_name = "hamster-kombat"

    game_model = cast("Game", apps.get_model("core", "Game"))
    game_model.objects.create(
        hash_name=hash_name,
        name=game_model.GAMES_DICT[hash_name],
        is_active=True,
    )


class Migration(migrations.Migration):
    """Миграция для создания модели Game."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "hash_name",
                    models.CharField(help_text="Game hash name", max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(help_text="Game name", max_length=255)),
                ("is_active", models.BooleanField(help_text="Is game active")),
            ],
        ),
        migrations.RunPython(
            code=add_initial_game,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
