# Generated by Django 5.0.6 on 2024-06-28 15:05
from typing import TYPE_CHECKING, cast

from django.db import migrations, models

from app.core.apps.core.models import Game

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def add_initial_game(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    """Добавление начальной игры."""
    game_id = "hamster-kombat"

    game_model = cast(Game, apps.get_model("core", "Game"))
    game_model.objects.create(
        id=game_id,
        name=Game.GAMES_DICT[game_id],
        is_active=True,
    )


class Migration(migrations.Migration):
    """Миграция для создания моделей Game, Payment и Customer."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigIntegerField(help_text="User ID", primary_key=True, serialize=False)),
                ("first_name", models.CharField(help_text="First name", max_length=150)),
                ("last_name", models.CharField(help_text="Last name", max_length=150, null=True)),
                ("username", models.CharField(help_text="Username", max_length=150, null=True)),
                ("refresh_token", models.CharField(db_index=True, help_text="Refresh token", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.CharField(help_text="Game ID", max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Game name", max_length=255)),
                ("is_active", models.BooleanField(help_text="Is game active")),
            ],
        ),
        migrations.RunPython(
            code=add_initial_game,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.CharField(help_text="Payment ID", max_length=64, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=6, help_text="Payment amount", max_digits=16)),
                ("is_payed", models.BooleanField(help_text="Is payment payed")),
            ],
        ),
    ]
