# Generated by Django 5.0.6 on 2024-06-28 06:09
from typing import TYPE_CHECKING, cast

from django.db import migrations, models

from app.core.apps.core.models import Game

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def add_initial_game(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    """Добавление начальной игры."""
    game_id = "hamster-kombat"

    game_model = cast(Game, apps.get_model("core", "Game"))
    game_model.objects.create(
        id=game_id,
        name=Game.GAMES_DICT[game_id],
        is_active=True,
    )


class Migration(migrations.Migration):
    """Миграция для создания модели Game."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.CharField(help_text="Game ID", max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Game name", max_length=255)),
                ("is_active", models.BooleanField(help_text="Is game active")),
            ],
        ),
        migrations.RunPython(
            code=add_initial_game,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
