# Generated by Django 5.0.6 on 2024-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения поля amount в модели Payment."""

    dependencies = [
        ("core", "0002_payment_created_at_alter_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=0, help_text="Payment amount", max_digits=32),
        ),
    ]
